version: '3.3'

#########################
# 1. docker-compose
#########################

# 컨테이너 서비스
services:
  # proxy 설정
  proxy:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - proxy/default.conf:/etc/nginx/conf.d/default.conf
      - proxy/nginx.conf:/etc/nginx/nginx.conf
      - cert:/app/cert
      - web:/var/www/html
    restart: always
    depends_on:
      - blog
    networks:
      - web-network

  # web
  blog:
    image: wordpress:6.5.3-php8.3-fpm
    user: '1000'
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: /run/secrets/blog_db_user
      WORDPRESS_DB_PASSWORD: /run/secrets/blog_db_password
      WORDPRESS_DB_NAME: 'blog'
    volumes:
      - web:/var/www/html
    restart: always
    depends_on:
      - db
    networks:
      - web-network

  # db
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_DATABASE: blog
      MYSQL_USER: /run/secrets/blog_db_user
      MYSQL_PASSWORD: /run/secrets/blog_db_password
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db/mysql:/var/lib/mysql:rw
    restart: always
    networks:
      - web-network

# doker-compose.yml 위치에 db
secrets:
  blog_db_password:
    file: db/pwd
  blog_db_user:
    file: db/use

networks:
  web-network:
    driver: bridge
#########################
# 2. proxy/default.conf
#########################

# server {
#     listen 80;
#     server_name eocis.app;

#     location / {
#         rewrite ^ https://$host$request_uri? permanent;
#     }
# }

# server {
#     listen 443 ssl http2;
#     listen [::]:443 ssl http2;
#     server_name eocis.app;

#   root /var/www/html;

#   index index.php;

#   location / {
#     try_files $uri $uri/ /index.php?$args;
#   }

#   rewrite /wp-admin$ $scheme://$host$uri/ permanent;

#   location ~ [^/]\.php(/|$) {
#     fastcgi_split_path_info ^(.+?\.php)(/.*)$;
#     if (!-f $document_root$fastcgi_script_name) {
#       return 404;
#     }

#     include fastcgi_params;
#     fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
#     fastcgi_param PATH_INFO       $fastcgi_path_info;
#     fastcgi_param PATH_TRANSLATED $document_root$fastcgi_path_info;

#     fastcgi_pass   blog:9000;
#     fastcgi_index  index.php;
#   }

#     ssl_certificate /app/cert/eocis.app.cer;
#     ssl_certificate_key /app/cert/eocis.app.key;
#     ssl_prefer_server_ciphers on;
#     ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
# }

# 코드를 그대로 사용시 server_name, fastcgi_pass, ssl path 정도만 수정하면 되리라.

#########################
# 3. nginx.conf
#########################

# user  nginx;
# worker_processes  auto;

# error_log  /var/log/nginx/error.log notice;
# pid        /var/run/nginx.pid;

# events {
#     worker_connections  1024;
# }

# http {
#     include       /etc/nginx/mime.types;
#     default_type  application/octet-stream;

#     log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
#                       '$status $body_bytes_sent "$http_referer" '
#                       '"$http_user_agent" "$http_x_forwarded_for"';

#     access_log  /var/log/nginx/access.log  main;

#     sendfile        on;
#     #tcp_nopush     on;

#     keepalive_timeout  65;

#     gzip  on;

#     include /etc/nginx/conf.d/*.conf; // <-- 이 부분은 docker-compose의 설정대로 따라가면된다.(default.conf)
# }
